host_rabbit: ${RABBIT_HOST:192.168.15.103}
user_rabbit: ${RABBIT_USER:api}
pass_rabbit: ${RABBIT_PASSWORD:api@user}
port_rabbit: ${RABBIT_PORT:5672}
events:
  origin:
    user-auth-created: spring-rabbitmq:auth?queues=communication.user.auth.created&routingKey=event.user-auth.created&exchangeType=topic&prefetchCount=100&autoDeclare=true

